export const SET_SELECTED_CITY_DATA = 'SET_SELECTED_CITY_DATA';
export const RECIEVE_WEATHER_DATA_FOR_CITY = 'RECIEVE_WEATHER_DATA_FOR_CITY';
export const SET_SELECTED_FORECAST = 'SET_SELECTED_FORECAST';
export const CLEAR_SELECTED_FORECAST = 'CLEAR_SELECTED_FORECAST';